In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

csv_file = '/content/drive/MyDrive/전처리데이터/review.csv'
df = pd.read_csv(csv_file, encoding='utf-8-sig')

df.tail()

,user,user_ID,type,tone,LABEL-4,LABEL-5,name_product,total_score,pigmentation,longevity,application,hydration
3623,yunjw****,2395.0,NaN,NaN,NaN,NaN,바닐라코_쉬어벨벳베일틴트_빈티지멜로우,5.0,3.0,3.0,3.0,3.0
3624,zeeesuu,2396.0,NaN,여름쿨톤,NaN,NaN,3CE_소프트매트립스틱_ WAYBACK,5.0,3.0,3.0,3.0,3.0
3625,zz605zn,2397.0,NaN,쿨톤,NaN,NaN,키스미_아이라이트블러리픽싱틴트_릿치레드,5.0,3.0,3.0,3.0,3.0
3626,zzzzxc,2398.0,NaN,NaN,NaN,NaN,키스미_아이라이트블러리픽싱틴트_릿치레드,5.0,2.0,2.0,2.0,2.0
3627,NaN,NaN,NaN,NaN,NaN,NaN,데이지크_멜팅캔디밤_,NaN,NaN,NaN,NaN,NaN

In [ ]:
df1 = df[['name_product', 'hydration']]
df1.tail()

               name_product  hydration
3623   바닐라코_쉬어벨벳베일틴트_빈티지멜로우        3.0
3624  3CE_소프트매트립스틱_ WAYBACK        3.0
3625  키스미_아이라이트블러리픽싱틴트_릿치레드        3.0
3626  키스미_아이라이트블러리픽싱틴트_릿치레드        2.0
3627            데이지크_멜팅캔디밤_        NaN

In [ ]:

# 'name_product'별로 'longevity'의 평균 계산
df_avg = df.groupby('name_product')['hydration'].mean().reset_index()

# 결과를 새로운 파일로 저장
output_file = '/content/drive/MyDrive/전처리데이터/average_hydration.csv'
df_avg.to_csv(output_file, index=False, encoding='utf-8-sig')

# 결과 확인
df_avg.tail()

          name_product  hydration
419  피브_컬러드롭립틴트_애프터스쿼트   2.750000
420    피브_컬러드롭립틴트_위티플럼   2.750000
421    피브_컬러드롭립틴트_칠링칠리   2.833333
422    피브_컬러드롭립틴트_피터패트   2.736842
423    피브_컬러드롭립틴트_허밍모브   3.000000

In [19]:
import pandas as pd

csv_file1 = '/content/drive/MyDrive/average_hl.csv'
df111 = pd.read_csv(csv_file1, index=False, encoding='utf-8-sig')

df111.tail()

TypeError: read_csv() got an unexpected keyword argument 'index'

In [4]:
import pandas as pd

csv_file1 = '/content/drive/MyDrive/average_hl.csv'
df1 = pd.read_csv(csv_file1,index=False, encoding='utf-8-sig')

df1.tail()

TypeError: read_csv() got an unexpected keyword argument 'index'